version: "3.8"
services:

  db:
    container_name: db
    image: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: tripscrud
      POSTGRES_PASSWORD: password

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "5050:80"

  app:
    container_name: app
    build: ./crud
    command: bash -c "alembic upgrade head && python main.py"
    volumes:
      - ./crud:/crud
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  db_data:
  pgadmin_data: